LOGGING_COMMON: &logging_common
    version: 1
    formatters:
        default:
            format: "[%(asctime)s] %(levelname)s %(name)s in %(module)s.%(funcName)s( %(lineno)s ): %(message)s"

        console:
            format: "%(asctime)s %(levelname)s %(name)s in %(module)s: %(message)s"

    handlers: &logging_handlers
        console:
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: console
            level: DEBUG

        logfile:
            class: logging.handlers.RotatingFileHandler
            filename: solar-webapp.log
            maxBytes: 10485760
            backupCount: 7
            formatter: default
            level: DEBUG

    root:
        level: DEBUG
        handlers:
        -   console
        -   logfile

    loggers:
        flask.app:
            level: DEBUG

COMMON: &common
    SECRET_KEY:                         insecure
    HOST:                               0.0.0.0
    PORT:                               8000
    DEBUG:                              true
    TESTING:                            true
    API_MODULE:                         solar
    LOGGING:
        <<: *logging_common

    BCRYPT_LOG_ROUNDS:                  13
    DEBUG_TB_INTERCEPT_REDIRECTS:       false
    CACHE_TYPE:                         simple
    SQLALCHEMY_TRACK_MODIFICATIONS:     false
    JWT_AUTH_USERNAME_KEY:              id
    JWT_AUTH_HEADER_PREFIX:             Authorization
    JWT_HEADER_TYPE:                    JWT
    JWT_EXPIRATION_DELTA:               weeks=52
    ACCESS_TOKEN_EXPIRES:               days=365
    ALLOW_CORS_ORIGIN:                  false
    CORS_ORIGIN_WHITELIST: []
    SQLALCHEMY_POOL_RECYCLE:            28799

COMMON_PROD:    &common_prod
    <<: *common
    PORT:                               80
    DEBUG:                              false
    TESTING:                            false

DATABASE:   &database
    ENGINE:                             mysql+pymysql
    USERNAME:                           testrunweb
    PASSWORD:                           testrunweb
    SCHEMA:                             TESTTOOL_DEV
    HOST:                               sts20029
    PORT:                               3306

DEVELOPMENT:    &development
    <<: *common
    ENV:                                dev
    LOGGING_FOLDER:                     /home/mbertens/src/python/solar/log
    APP_PATH:                           /home/mbertens/src/python/solar
    ANGULAR_PATH:                       /home/mbertens/src/python/solar/frontend/dist/angular-app
    DATABASE:
        <<: *database

STAGING:
    <<: *common_prod
    SECRET_KEY:                         sortasecure
    ENV:                                staging
    DEBUG:                              true
    TESTING:                            true
    LOGGING_FOLDER:                     /var/log/solar/pilot
    APP_PATH:                           /opt/pilot/solar
    ANGULAR_PATH:                       /opt/pilot/solar/frontend/dist/angular-app
    DATABASE:
        <<: *database

PRODUCTION:
    <<: *common_prod
    SECRET_KEY:                         shouldbereallysecureatsomepoint
    ENV:                                prod
    LOGGING_FOLDER:                     /var/log/solar/prod
    APP_PATH:                           /opt/prodution/solar
    ANGULAR_PATH:                       /opt/prodution/solar/frontend/dist/angular-app
    DATABASE:
        <<: *database
        SCHEMA:                         SOLAR

COMMON_TASKS:
    webapp:
        LOGGING.handlers.logfile.filename: solar-webapp.log
    task1:
        LOGGING.handlers.logfile.filename: task1.log
        DATABASE:
            USERNAME:   pe2mbs
    task2:
        LOGGING.handlers.logfile.filename: task2.log
