#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2020 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2020-12-06 15:51:25 version 2.0.607 by user mbertens
#
import webapp2.api as API
from webapp2.common.parameters import SerializationDictField


class UserSchema( API.mm.SQLAlchemySchema
                        ):
    """Schema for the gn_user table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    class Meta:
        #model = User
        fields = [
            'U_ID',
            'U_ACTIVE',
            'U_NAME',
            'U_ROLE',
            'U_HASH_PASSWORD',
            'U_MUST_CHANGE',
            'U_FIRST_NAME',
            'U_MIDDLE_NAME',
            'U_LAST_NAME',
            'U_EMAIL',
            'U_ACCESS_TOKEN',
            'U_REFRESH_TOKEN',
            'U_TOKEN_DT',
            'U_CREATE_DT',
            'U_MOD',
            'U_MOD_USER',
            'U_REMARK',
            'U_LOCALE',
            'U_LISTITEMS',
            'U_ACTIVE_LABEL',
            'U_ROLE_FK',
            'U_LOCALE_LABEL',
            'U_LISTITEMS_LABEL',
        ]
    U_ACTIVE_LABEL          = SerializationDictField( attribute="U_ACTIVE",
                                                      dictionary = {True: 'Yes', False: 'No'} )
    U_ROLE_FK               = API.mm.Nested( 'RoleSchema' )
    U_LOCALE_LABEL          = SerializationDictField( attribute="U_LOCALE",
                                                      dictionary = {1: 'nl_NL'} )
    U_LISTITEMS_LABEL       = SerializationDictField( attribute="U_LISTITEMS",
                                                      dictionary = {5: '5 Records', 10: '10 Records', 25: '25 Records', 100: '100 Records'} )

gn_userSchema   = UserSchema()
gn_usersSchema  = UserSchema( many = True )


