#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018-2021 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   gencrud: 2021-02-27 07:09:13 version 2.1.666 by user mbertens
#
import webapp2.api as API
from webapp2.common.parameters import SerializationDictField


class NewsSchema( API.mm.SQLAlchemySchema ):
    """Schema for the news table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    class Meta:
        fields = [ "N_ID", "N_MESSAGE", "N_ACTIVE", "N_ACTIVE_LABEL", "N_ALERT", "N_ALERT_LABEL", "N_KEEP", "N_KEEP_LABEL", "N_START_DATE", "N_END_DATE", "N_REMARK" ]

    N_ACTIVE_LABEL          = SerializationDictField( attribute="N_ACTIVE",
                                                      dictionary = {True: 'Yes', False: 'No'} )
    N_ALERT_LABEL           = SerializationDictField( attribute="N_ALERT",
                                                      dictionary = {True: 'Yes', False: 'No'} )
    N_KEEP_LABEL            = SerializationDictField( attribute="N_KEEP",
                                                      dictionary = {True: 'Yes', False: 'No'} )

newsSchema   = NewsSchema()
newssSchema  = NewsSchema( many = True )

