"""empty message

Revision ID: 2020_01
Revises: 
Create Date: 2020-12-05 15:37:37.134143

"""
from alembic import op
import sqlalchemy as sa
import webapp2.extensions.database

# revision identifiers, used by Alembic.
revision = '2020_01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_feedback',
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=50), nullable=False),
    sa.Column('f_type', sa.Integer(), nullable=False),
    sa.Column('f_voted', sa.Integer(), nullable=False),
    sa.Column('f_subject', sa.String(length=100), nullable=False),
    sa.Column('f_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('f_id', name=op.f('pk_ap_feedback'))
    )
    op.create_table('gn_role',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('r_role', sa.String(length=255), nullable=False),
    sa.Column('r_mod', sa.DateTime(), nullable=False),
    sa.Column('r_user_mod', sa.String(length=30), nullable=False),
    sa.Column('r_remark', webapp2.extensions.database.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('r_id', name=op.f('pk_gn_role'))
    )
    op.create_table('gn_user',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('u_active', sa.Boolean(), nullable=True),
    sa.Column('u_name', sa.String(length=30), nullable=False),
    sa.Column('u_role', sa.Integer(), nullable=True),
    sa.Column('u_hash_password', sa.String(length=255), nullable=False),
    sa.Column('u_must_change', sa.Boolean(), nullable=True),
    sa.Column('u_first_name', sa.String(length=50), nullable=False),
    sa.Column('u_middle_name', sa.String(length=50), nullable=True),
    sa.Column('u_last_name', sa.String(length=50), nullable=False),
    sa.Column('u_email', sa.String(length=100), nullable=False),
    sa.Column('u_access_token', sa.String(length=512), nullable=True),
    sa.Column('u_refresh_token', sa.String(length=512), nullable=True),
    sa.Column('u_token_dt', sa.DateTime(), nullable=True),
    sa.Column('u_create_dt', sa.DateTime(), nullable=True),
    sa.Column('u_mod', sa.DateTime(), nullable=False),
    sa.Column('u_mod_user', sa.String(length=30), nullable=False),
    sa.Column('u_remark', webapp2.extensions.database.LONGTEXT(), nullable=True),
    sa.Column('u_locale', sa.Integer(), nullable=True),
    sa.Column('u_listitems', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_role'], ['gn_role.r_id'], name=op.f('fk_gn_user_u_role_gn_role')),
    sa.PrimaryKeyConstraint('u_id', name=op.f('pk_gn_user'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gn_user')
    op.drop_table('gn_role')
    op.drop_table('ap_feedback')
    ### end Alembic commands ###
